language: java
sudo: false # faster builds
before_script:
  # start xvfb to run a virtual frame buffer (pretend to have a monitor)
  - "export DISPLAY=:99.0"
  - sudo apt-get install -qq --force-yes mesa-utils 
  - sudo apt-get install -qq --force-yes libx11-6 
  - sudo apt-get install -qq --force-yes libgl1-mesa-swx11 
  - sudo apt-get install -qq --force-yes libgl1-mesa-swx11-dev 
  - sudo apt-get install -qq --force-yes xvfb  
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render
  #- "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script: 
  - mvn test -B